name: Run Postman Tests

on:
  push:
    branches:
      - main

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        run: |
          newman run "My Collection.postman_collection.json" \
          -e "QA-env.postman_environment.json"
